"""
FastAPI server — OpenEnv adapter for FinanceEnv.

Problem: openenv creates a fresh env instance per HTTP request (stateless),
but FinanceEnv is stateful (step requires the same instance that reset ran on).
Solution: FinanceEnvAdapter delegates all calls to a module-level singleton.

Endpoints (auto-generated by openenv):
    POST /reset   → Observation
    POST /step    → StepResponse (observation + reward + done)
    GET  /state   → State
    GET  /health  → {"status": "ok"}
    GET  /schema  → action/observation JSON schemas
    GET  /docs    → Swagger UI
"""

from __future__ import annotations

from typing import Any, Optional

from openenv.core.env_server import Environment as OpenEnvEnvironment, create_fastapi_app

from finance_env import FinanceEnv
from finance_env.models import Action, Observation, State

# Single shared instance — persists state across all HTTP requests
_singleton = FinanceEnv()


class FinanceEnvAdapter(OpenEnvEnvironment):
    """Thin adapter: satisfies openenv's Environment interface, delegates to the singleton."""

    def __init__(self) -> None:
        super().__init__()
        self._env = _singleton

    def reset(
        self,
        seed: Optional[int] = None,
        episode_id: Optional[str] = None,
        task_id: Optional[str] = None,
        **kwargs: Any,
    ) -> Observation:
        return self._env.reset(seed=seed, episode_id=episode_id, task_id=task_id, **kwargs)

    def step(self, action: Action, timeout_s: Optional[float] = None, **kwargs: Any) -> Observation:
        # env.step() returns a 4-tuple; extract done + cumulative_score and embed in Observation
        obs, reward, done, _ = self._env.step(action)
        obs.done = done
        obs.reward = reward.cumulative_score
        return obs

    @property
    def state(self) -> State:
        # Must be a property — openenv accesses _env.state, not _env.state()
        return self._env.state()


app = create_fastapi_app(
    FinanceEnvAdapter,   # passed as a class (factory), not an instance
    action_cls=Action,
    observation_cls=Observation,
)


def main() -> None:
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=7860)


if __name__ == "__main__":
    main()
